Repository microsoft/mu_feature_config, pull requests merged in 2022-12, with the labels that each got.

#76 Added binary CSV column
  SetupDataPkg/Tools/VariableList.py
Labels: language:python, impact:non-functional

#77 Allow arbitrary SVD values to be set through ConfApp
  SetupDataPkg/ConfApp/SetupConf.c
  SetupDataPkg/ConfApp/UnitTest/ConfAppSetupConfUnitTest.c
  SetupDataPkg/ConfApp/UnitTest/ConfAppUnitTestCommon.c
  SetupDataPkg/Test/Include/Good_Config_Data.h
Labels: impact:testing

#82 Added python script to write dumpstore bin to variables from windows
  SetupDataPkg/SetupDataPkg.ci.yaml
  SetupDataPkg/Tools/WriteConfVarListToUefiVars.py
Labels: language:python

#80 Remove update configuration from network packet option
  SetupDataPkg/ConfApp/ConfApp.h
  SetupDataPkg/ConfApp/SetupConf.c
  SetupDataPkg/ConfApp/UnitTest/ConfAppSetupConfUnitTest.c
Labels: impact:testing

#81 Updated dump option to put all variables into SVD format
  SetupDataPkg/ConfApp/SetupConf.c
  SetupDataPkg/ConfApp/UnitTest/ConfAppSetupConfUnitTest.c
  SetupDataPkg/ConfApp/UnitTest/ConfAppUnitTestCommon.c
Labels: impact:testing
