Repository microsoft/mu_feature_config, pull requests merged in 2023-02, with the labels that each got.

#99 Update CI
  .azurepipelines/Ubuntu-GCC5.yml
  .azurepipelines/Windows-VS.yml
  .pytool/CISettings.py
  basecore_ext_dep.yaml
  mu_plus_ext_dep.yaml
  mu_tiano_ext_dep.yaml
  pip-requirements.txt
  py-requirements.txt
Labels: impact:non-functional

#92 Updated setup script to publish single binary file
  .cspell.json
  SetupDataPkg/Tools/ConfigEditor.py
  SetupDataPkg/Tools/VariableList.py
  SetupDataPkg/Tools/setup.py
Labels: language:python, impact:breaking-change

#106 Restrict byte aligned struct packing to schema defined elements
  SetupDataPkg/Tools/KnobService.py
Labels: language:python

#111 Add Newline to KnobService.py Output
  SetupDataPkg/Tools/KnobService.py
Labels: type:bug, impact:non-functional

#116 SetupDataPkg.dsc: Add stack cookie support libs
  SetupDataPkg/SetupDataPkg.ci.yaml
  SetupDataPkg/SetupDataPkg.dsc
Labels: type:bug, impact:non-functional

#120 Fix a TypeError when generating knob profiles
  SetupDataPkg/Tools/KnobService.py
Labels: language:python, impact:non-functional
