Repository microsoft/mu_feature_config, pull requests merged in 2023-06, with the labels that each got.

#196 Create GENERIC_PROFILE_INDEX Macro
  SetupDataPkg/Include/Library/ActiveProfileIndexSelectorLib.h
  SetupDataPkg/Library/ActiveProfileIndexSelectorLibNull/ActiveProfileIndexSelectorLibNull.c
Labels: impact:non-functional

#207 Update autogen script for profile names on UEFI builds
  .cspell.json
  SetupDataPkg/Include/ConfigStdStructDefs.h
  SetupDataPkg/Include/Library/PlatformConfigDataLib.h
  SetupDataPkg/Library/PlatformConfigDataLibNull/PlatformConfigDataLibNull.c
  SetupDataPkg/Library/PlatformConfigDataLibNull/PlatformConfigDataLibNull.inf
  SetupDataPkg/Plugins/UpdateConfigHdr/UpdateConfigHdr.py
  SetupDataPkg/SetupDataPkg.dec
  SetupDataPkg/SetupDataPkg.dsc
  SetupDataPkg/Tools/KnobService.py
Labels: language:python

#210 The profile name variable should be a string array
  SetupDataPkg/Include/Library/PlatformConfigDataLib.h
  SetupDataPkg/Library/PlatformConfigDataLibNull/PlatformConfigDataLibNull.c
  SetupDataPkg/Tools/KnobService.py
Labels: type:bug, language:python, impact:non-functional
