Repository microsoft/mu_feature_config, pull requests merged in 2023-07, with the labels that each got.

#218 Move ConfigKnobShimStandaloneMmLib to ConfigKnobShimMmLib
  SetupDataPkg/Library/ConfigKnobShimLib/ConfigKnobShimMmLib/ConfigKnobShimMmLib.c
  SetupDataPkg/Library/ConfigKnobShimLib/ConfigKnobShimMmLib/ConfigKnobShimMmLib.inf
  SetupDataPkg/Library/ConfigKnobShimLib/ConfigKnobShimMmLib/UnitTest/ConfigKnobShimMmLibUnitTest.inf
  SetupDataPkg/SetupDataPkg.dsc
  SetupDataPkg/Test/SetupDataPkgHostTest.dsc
Labels: impact:breaking-change

#219 Move ConfigKnobShimMmLib to MM_STANDALONE module type
  SetupDataPkg/Library/ConfigKnobShimLib/ConfigKnobShimMmLib/ConfigKnobShimMmLib.inf
Labels: impact:non-functional

#213 Fixing document to reflect the current state
  SetupDataPkg/Docs/Overview/Overview.md
  SetupDataPkg/Docs/PlatformIntegration/PlatformIntegrationSteps.md
Labels: type:documentation, impact:non-functional
