Repository microsoft/mu_feature_config, pull requests merged in 2023-03, with the labels that each got.

#129 Add XML Config Documentation
  SetupDataPkg/Docs/ConfigurationFiles/ConfigurationFiles.md
  SetupDataPkg/Docs/ConfigurationFiles/Images/ConfigEditorOptions.png
  SetupDataPkg/Docs/Overview/Images/app_view_boot.png
  SetupDataPkg/Docs/Overview/Images/app_view_dump.png
  SetupDataPkg/Docs/Overview/Images/app_view_info.png
  SetupDataPkg/Docs/Overview/Images/app_view_menu.png
  SetupDataPkg/Docs/Overview/Images/app_view_secure.png
  SetupDataPkg/Docs/Overview/Images/app_view_update.png
  SetupDataPkg/Docs/Overview/Images/app_work_flow.png
  SetupDataPkg/Docs/Overview/Images/build_work_flow.png
  SetupDataPkg/Docs/Overview/Images/conf_edit_view.png
  SetupDataPkg/Docs/Overview/Images/conf_edit_work_flow.png
  SetupDataPkg/Docs/Overview/Images/conf_update_view.png
  SetupDataPkg/Docs/Overview/Images/mu_feature_configworkflows.png
  SetupDataPkg/Docs/Overview/Overview.md
  SetupDataPkg/Docs/PlatformIntegration/PlatformIntegrationSteps.md
  SetupDataPkg/Docs/PlatformIntegration/SoftwareComponentOverview.md
  SetupDataPkg/Docs/Profiles/Overview.md
Labels: type:documentation, impact:non-functional

#136 Add CodeQL Stuart parameter to this repo
  .pytool/CISettings.py
Labels: impact:non-functional

#135 Correctly Print Validation Function for Standalone Enums in KnobService.py
  SetupDataPkg/Tools/KnobService.py
Labels: language:python

#140 Unify pip-requirements from tools and base repo
  ReadMe.rst
  SetupDataPkg/Tools/pip-requirements.txt
  pip-requirements.txt
Labels: complexity:easy, type:documentation, impact:non-functional

#145 Fixing GenBin command line option
  SetupDataPkg/Tools/GenNCCfgData.py
  SetupDataPkg/Tools/GenNCCfgData_test.py
Labels: language:python

#149 Adding capability for reading configuration knobs from host OS
  .cspell.json
  SetupDataPkg/Tools/ReadUefiVarsToConfVarList.py
  SetupDataPkg/Tools/SettingSupport/UefiVariablesSupportLib.py
Labels: language:python
