Repository microsoft/mu_feature_config, pull requests merged in 2023-09, with the labels that each got.

#244 Updated auto-gen script to accept cache for policy values
  SetupDataPkg/Docs/PlatformIntegration/PlatformIntegrationSteps.md
  SetupDataPkg/Tools/KnobService.py
Labels: language:python, type:documentation

#247 .pytool/CISettings.py: Update from 202208 to 202302
  .pytool/CISettings.py
Labels: impact:non-functional, semver:patch

#251 SetupDataPkg: Fix GCC failure in KnobService.py
  SetupDataPkg/Tools/KnobService.py
Labels: type:bug, language:python, impact:non-functional
