Repository microsoft/mu_feature_config, pull requests merged in 2024-07, with the labels that each got.

#378 UpdateConfigHdr: Gracefully exit when filepath is `None`
  SetupDataPkg/Plugins/UpdateConfigHdr/UpdateConfigHdr.py
Labels: type:bug, language:python, impact:non-functional

#381 SetupDataPkg/ConfApp: Fix incorrect type used in a GUID print
  SetupDataPkg/ConfApp/SetupConf.c
Labels: impact:non-functional

#380 Removing script that would create windows executable from a python file.
  SetupDataPkg/Tools/setup.py
Labels: language:python, impact:non-functional
