Repository microsoft/mu_feature_config, pull requests merged in 2024-06, with the labels that each got.

#369 SetupDataPkg/ConfigKnobShimLib: Correct unit test compilation errors.
  SetupDataPkg/Library/ConfigKnobShimLib/ConfigKnobShimDxeLib/GoogleTest/ConfigKnobShimDxeLibGoogleTest.inf
  SetupDataPkg/Library/ConfigKnobShimLib/ConfigKnobShimDxeLib/UnitTest/ConfigKnobShimDxeLibUnitTest.inf
  SetupDataPkg/Library/ConfigKnobShimLib/ConfigKnobShimMmLib/ConfigKnobShimMmLib.inf
  SetupDataPkg/Library/ConfigKnobShimLib/ConfigKnobShimMmLib/UnitTest/ConfigKnobShimMmLibUnitTest.inf
  SetupDataPkg/Library/ConfigKnobShimLib/ConfigKnobShimPeiLib/ConfigKnobShimPeiLib.inf
  SetupDataPkg/Library/ConfigKnobShimLib/ConfigKnobShimPeiLib/UnitTest/ConfigKnobShimPeiLibUnitTest.inf
  SetupDataPkg/Library/ConfigKnobShimLib/UnitTest/ConfigKnobShimLibUnitTestCommon.c
Labels: impact:non-functional

#370 Switch to using 202311 branchs of required repos instead of 202302
  .pytool/CISettings.py
Labels: impact:non-functional

#371 SetupDataPkg/ConfigKnobShimPeiLib: Revert ConfigKnobShimPeiLib change and fix unit test.
  SetupDataPkg/Library/ConfigKnobShimLib/ConfigKnobShimPeiLib/ConfigKnobShimPeiLib.inf
  SetupDataPkg/Library/ConfigKnobShimLib/ConfigKnobShimPeiLib/GoogleTest/ConfigKnobShimPeiLibGoogleTest.inf
Labels: impact:non-functional

#368 SetupDataPkg/Tools/setup.py: Expand script to publish binaries for ReadUefiVarsToConfVarList, WriteConfVarListToUefiVars.
  .gitignore
  SetupDataPkg/Tools/setup.py
Labels: language:python, impact:non-functional

#357 Required changes to KnobService and XML Schema to enable per-library header definitions and XML merging
  .cspell.json
  SetupDataPkg/Docs/ConfigurationFiles/ConfigurationFiles.md
  SetupDataPkg/Docs/PlatformIntegration/PlatformIntegrationSteps.md
  SetupDataPkg/Tools/KnobService.py
  SetupDataPkg/Tools/VariableList.py
  SetupDataPkg/Tools/configschema.xsd
  SetupDataPkg/Tools/sampleschema.xml
Labels: language:python, impact:non-functional

#374 Add Multiple Config Environment Build Support
  SetupDataPkg/Docs/PlatformIntegration/PlatformIntegrationSteps.md
  SetupDataPkg/Docs/Profiles/Overview.md
  SetupDataPkg/Plugins/UpdateConfigHdr/UpdateConfigHdr.py
Labels: language:python, type:documentation, impact:non-functional
