Repository microsoft/mu_feature_config, pull requests merged in 2024-12, with the labels that each got.

#425 Add missing gSchemaXmlHash in PlatformConfigDataLibNull.c
  SetupDataPkg/Library/PlatformConfigDataLibNull/PlatformConfigDataLibNull.c
Labels: impact:non-functional

#429 Correct the ESC behavior in ConfigApp
  SetupDataPkg/ConfApp/BootOptions.c
Labels: type:bug, impact:non-functional

#424 Add search function for Config Editor
  SetupDataPkg/Tools/ConfigEditor.py
  SetupDataPkg/Tools/VariableList.py
Labels: language:python, type:enhancement, impact:non-functional
