Repository microsoft/mu_feature_config, pull requests merged in 2024-08, with the labels that each got.

#362 Switch to use edk2-pytool-library UefiVariableSupportLib.
  .cspell.json
  SetupDataPkg/SetupDataPkg.ci.yaml
  SetupDataPkg/Tools/ReadUefiVarsToConfVarList.py
  SetupDataPkg/Tools/SettingSupport/PyRobotRemote.py
  SetupDataPkg/Tools/SettingSupport/UefiVariablesSupportLib.py
  SetupDataPkg/Tools/SettingSupport/UefiVariablesSupportLinuxLib.py
  SetupDataPkg/Tools/WrapAndSetSvd.py
  SetupDataPkg/Tools/WriteConfVarListToUefiVars.py
Labels: language:python

#365 New write_csv_detailed() to dump out data in expanded format
  SetupDataPkg/Tools/VariableList.py
Labels: language:python, impact:non-functional

#394 Update CI branches to release/202405
  .pytool/CISettings.py
Labels: impact:non-functional
